### ISSUE TITLE
Changesets GithubAction not creating github releases

### ISSUE THREAD

**Issue by gyfchong** [changesets/changesets#1202]
## Affected Packages

`action`

## Problem

`createGithubReleases` is not listening to it's default `true` setting, which required us to set to `true` manually:
https://github.com/cultureamp/kaizen-design-system/blob/main/.github/workflows/changeset.yaml#L29

**Comment by gyfchong** [comment]
Sorry, was looking in the wrong place. This works as expected.

**Comment by alvesvaren** [comment]
I have the same issue, where's the correct place to look? :eyes:

**Comment by msaeedsaeedi** [comment]
@gyfchong How did you fix this?

**Comment by msaeedsaeedi** [comment]
## For Future Readers
- Use PAN (Personal Access Token) instead of `GITHUB_TOKEN`.
- Update Repository setting `Actions` -> `General` -> `Workflow permissions`
   - set `read-write` permissions
   - set create and approve pull requests
- Give PAN Permissions
   - Contents `read-write`
   - Pull requests `read-write`  

After the PR is generated and merged the actions will be automatically triggered and will create github release.

Hope this works.

**Comment by yamcodes** [comment]
> ## For Future Readers
> 
>     * Use PAN (Personal Access Token) instead of `GITHUB_TOKEN`.
> 
>     * Update Repository setting `Actions` -> `General` -> `Workflow permissions`
>       
>       * set `read-write` permissions
>       * set create and approve pull requests
> 
>     * Give PAN Permissions
>       
>       * Contents `read-write`
>       * Pull requests `read-write`
> 
> 
> After the PR is generated and merged the actions will be automatically triggered and will create github release.
> 
> Hope this works.

Just a small correction, it's PAT, not PAN.
