### ISSUE TITLE
Action succeeds but package is never published to npm

### ISSUE THREAD

**Issue by Oudwins** [changesets/changesets#1280]
## Affected Packages

I am making a new package, haven't been able to make first publish.

## Problem

I am trying to use the github action to publish the package to npm, the action succeeds but it does not fail but it does not publish it. No idea what is happening.

repo: https://github.com/Oudwins/dstyler

## Details on errors which might be related

```bash
warn No unpublished projects to publish
```

**Comment by Oudwins** [comment]
Fixed this. It was because I had put "private": "false" on the package.json. I fixed it by deploying first through npm publish got the error and then I knew what to fix. It might be nice for the action to print any errors it gets from npm to the user?

**Comment by elcoosp** [comment]
I encountered this [issue](https://github.com/changesets/changesets/issues/1280#issuecomment-1849049563) after following this [documentation section](https://changesets-docs.vercel.app/versioning-apps#setting-up-a-package) - which may be revisited -. Caused by this field in `pnpm` workspace member `package.json`
```json
{
  "private": false
}
```
