### ISSUE TITLE
Security vulnerability in cross-spawn (sub-dependency of spawndamnit)

### ISSUE THREAD

**Issue by renet** [changesets/changesets#1513]
## Affected Packages

@changesets/cli

## Problem

A security vulnerability popped up lately with a sub-dependency of the `spawndamnit` dependency that is used within the `cli` package of this monorepo:

> Versions of the package cross-spawn before 7.0.5 are vulnerable to Regular Expression Denial of Service (ReDoS) due to improper input sanitization. An attacker can increase the CPU usage and crash the program by crafting a very large and well crafted string.

## Proposed solution

As `spawndamnit` hasn't been maintained in 7 years now, I'd recommend upgrading to a different package that offers the features but is actively maintained. I'm not familiar with this package, so I cannot give good recommendations.

**Comment by nicoalonsop** [comment]
This issue will be resolved if https://github.com/jamiebuilds/spawndamnit/pull/10 is merged and we bump the version here.

**Comment by herokwon** [comment]
I received the same alert from dependabot on the Security tab.
@nicoalonsop  Thanks. I've seen [it](https://github.com/jamiebuilds/spawndamnit/pull/10) a few minutes ago. It's worried a little bit because of the fact that package is so old version. But I hope that yours are merged.

![image](https://github.com/user-attachments/assets/b03121a8-dc89-4748-8e19-102d1d66455d)

**Comment by yuhengshs** [comment]
Hi, given that new `spawndamnit` is merged, do we expect the upgrade for `changeset/cli` will happen soon?

**Comment by nicoalonsop** [comment]
I’ll do my best to get it done today, but I can’t guarantee I’ll make it.
