### ISSUE TITLE
Removing dependencies with GPL licenses

### ISSUE THREAD

**Issue by RajaBellebon** [changesets/changesets#248]
## Affected Packages

* smartwrap 1.0.11
* smartwrap 1.0.9
* breakword 1.0.3

## Problem

In the new atlassian-frontend repository, we decided to not use packages that have GPL licences. Changeset CLI is bringing those two packages above.

## Proposed solution

We need to investigate how we can replace those dependencies.

**Comment by tunnckoCore** [comment]
Wrapping seems like totally unnecessary thing. Breaking the words too. I assume it's used in changelogs and releases, where i really don't see any sense to do it anyway.

**Comment by vhscom** [comment]
> In the new atlassian-frontend repository, we decided to not use packages that have GPL licences. Changeset CLI is bringing those two packages above.

How is this relevant to Changesets? This sounds like a project-specific decision. Given this issue is two years old now I presume it's no longer a concern and should be closed, yet? Finally, when companies use open source software they always have the option of reaching out to support software developers

**Comment by vhscom** [comment]
> In the new atlassian-frontend repository, we decided to not use packages that have GPL licences. Changeset CLI is bringing those two packages above.

How is this relevant to Changesets? This sounds like a project-specific decision. Given this issue is two years old now I presume it's no longer a concern and should be closed, yet? If it's still an issue, I'd suggest someone at Atlassian reach out to the smartwrap maintainer and ask them nicely if they could purchase a commercial license. In doing so, the company would be contributing to the sustainability of open source work.

**Comment by vhscom** [comment]
> In the new atlassian-frontend repository, we decided to not use packages that have GPL licences. Changeset CLI is bringing those two packages above.

How is this relevant to Changesets? It sounds more like a project-specific decision at Atlassian. Given this issue is two years old now I presume it's no longer a concern and should be closed? And if it's still an issue, I'd suggest someone at Atlassian reach out to the smartwrap copyright holder and ask them nicely if they could purchase a commercial license and use that instead.

**Comment by vhscom** [comment]
> In the new atlassian-frontend repository, we decided to not use packages that have GPL licences. Changeset CLI is bringing those two packages above.

How is this relevant to Changesets? It sounds more like a project-specific decision at Atlassian. Given this issue is two years old now I presume it's no longer a concern and should be closed. And if it's still an issue, I'd suggest someone at Atlassian reach out to the smartwrap copyright holder and ask them nicely if they could purchase a commercial license and use that instead.

**Comment by Andarist** [comment]
`smartwrap` is used within this call:
https://github.com/changesets/changesets/blob/c68536edf4c04e7fdf5594ec9c69471cd86fd0ce/packages/cli/src/commands/status/index.ts#L104
and `breakword` is a dependency of `smartwrap`

The `tty-table` package could be updated and that would make it include `smartwrap` that is already MIT licensed. However, the `breakword` package would still be under GPL. The license in the `breakword`'s repository has also been changed to MIT but this change has not been released to npm.

However, I'm not super sure if we could update `tty-table` now because the new version requires at least node 12 and I think that Changesets might currently work with lower version numbers of node and we don't have node version policy declared anywhere.

**Comment by matthew-vance** [comment]
any updates on this? we can no longer have gpl licenses in our codebase and it'd be a shame for us to have to remove changesets

**Comment by vhscom** [comment]
Large organizations such as Atlassian or other for-profit business interests with requirements to not have GPL-licensed dependencies in their repos are probably using Linux inside Docker and Linux is GPLv2 so how is using GPL software in dev tooling to create a changelog any different from building your Docker containers?

**Comment by Andarist** [comment]
@sethidden thank you for the ping! I rechecked the originally listed packages manually and I can confirm that they all are MIT now.
