### ISSUE TITLE
Changesets ignoring the skipCI config key

### ISSUE THREAD

**Issue by jordan-simonovski** [changesets/changesets#285]
## Affected Packages

`pkg:cli`

## Problem
Setting the config.json this way
```
{
  "$schema": "https://unpkg.com/@changesets/config@0.3.0/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": true,
  "skipCI": false,
  "linked": [],
  "access": "restricted",
  "baseBranch": "master"
}
```
when changesets commits in CI, the comit message still contains `skipCI`

**Comment by Noviny** [comment]
Hey, thanks for raising this! Couple of clarifications, do you have the repo where you are experiencing this problem, and to check, this error occurs with the changeset action creating commits for you?

**Comment by jordan-simonovski** [comment]
Hey @Noviny! 
The repo is sadly not on GitHub, but is a lerna repo that we're working on at the moment. Yeah, the error itself occurs when we run the following commands in our CI scripts:
```
echo "+++ :npm: Publishing to NPM :npm:"
yarn changeset version
yarn changeset publish 
```

**Comment by Noviny** [comment]
Had a really quick look into it, and we deprecated the `skipCI` flag with our version 2 upgrade, as all use-cases where people wanted commit: true, they also wanted `skipCI` true, and we add the `skipCI` flag to all our commits.

Happy to leave this open as 'we should reimplement this to allow fine-grained controls' but for an immediate fix you can set `commit` to `false` and run:

```shell
echo "+++ :npm: Publishing to NPM :npm:"
yarn changeset version
git add . && git commit -m "versioned packages"
yarn changeset publish 
```

My two take-aways from this is we should add skipCI back as its own flag, defaulting to `true` (what most people have wanted) and fine grain `commit` so you can set it per command that can commit.

Thanks for raising this!

**Comment by jordan-simonovski** [comment]
Ah right! Yeah we made a workaround using the manual commit in our CI pipelines. Thanks for doing such a great job on this project!

**Comment by wweaver** [comment]
I have an issue because with our PR merges all commits are condensed down to a single commit and the commit message contains all commit messages that are in the PR. So when the PR gets merged it has `[skipCi]` in there and the changesets workflow doesn't run as it should. I couldn't figure out a workaround so instead I've been reduced to having `{"commit": false}`. I would love to have a way to disable the `[skipCi]` from being added altogether. I understand the benefit that if it gets pushed to a particular PR then it shouldn't retrigger the build but that messes up our workflow. I couldn't figure out a way in github to not include all commit messages in the condensed commit that gets merged. Any thoughts would be appreciated.

**Comment by Andarist** [comment]
@wweaver it feels like this is the most up-to-date discussion about this issue: https://github.com/changesets/changesets/issues/688 . I didn't have time lately to revisit this but it's on my mind - I see there is already a PR trying to address this (potentially. I'll try to get to reviewing it soon(-ish)
