### ISSUE TITLE
prettier old version

### ISSUE THREAD

**Issue by dhrubabasu** [changesets/changesets#616]
## Affected Packages

apply-release-plan

## Problem

It's relying on an old version of prettier: https://github.com/atlassian/changesets/blob/main/packages/apply-release-plan/package.json#L20

## Proposed solution

Is it necessary to ship prettier as a dependency of this package? Could it be moved to devDependencies? If not, upgrade prettier to v2.

**Comment by Andarist** [comment]
@mitchellhamilton we could probably use an optional peer dependency here, wdyt? that way we could use whatever is installed by the user (conditionally) - the Prettier JS API probably didn't change much for what we need so it should be pretty straightforward to support its both major versions

**Comment by alexamy** [comment]
Hey! Today i'm stuck with these problem too. In yarn workspaces prettier from `bin` is referencing old version, and its caused by `apply-release-plan`. Any plans to fix this issue?

**Comment by Andarist** [comment]
> Hey! Today i'm stuck with these problem too. In yarn workspaces prettier from bin is referencing old version, and its caused by apply-release-plan. Any plans to fix this issue?

I'm not sure I understand this - a demo repository would be helpful. Are you saying that our `prettier` dependency (transitive one for you) "overrides" your direct dependency and is put within root's~ `.bin`?

**Comment by alexamy** [comment]
Yes, you are right. I will try to make a clean repository with this issue.

**Comment by alexamy** [comment]
In clean repo I can't repeat this. I think it's local error then, so its not `changesets` related. Thanks!

**Comment by Princesseuh** [comment]
We're running into an issue on the [Astro](https://astro.build) repo because of the Prettier version being so old. Prettier is trying to run our plugin (`prettier-plugin-astro`) on the embedded code blocks that use the `astro` language and since the plugin doesn't work on that version of Prettier (which admittedly, is 3 years old at this point), it just ends up totally nuking the code blocks, here's a diff from a changesets PR:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/3019731/183787785-4fe99b60-d88a-444f-9d45-595b7793179c.png">

For now, we'll just disable our plugins inside CHANGELOG.md, but it'd be cool to get this working!

**Comment by Andarist** [comment]
I've created a PR that, I hope, should fix most of the problems like this: https://github.com/changesets/changesets/pull/905
