### ISSUE TITLE
Change default base branch: master -> main

### ISSUE THREAD

**Issue by janosh** [changesets/changesets#675]
Since GitHub [changed the name of the default branch on new repos to `main`](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) on Oct 1, 2020, `changesets` might consider updating the default `baseBranch` to match:

```diff
$ yarn changeset init
$ cat .changeset/config.json
{
  "$schema": "https://unpkg.com/@changesets/config@1.6.2/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": false,
  "linked": [],
  "access": "restricted",
- "baseBranch": "master",
+ "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```

**Comment by Andarist** [comment]
There are might be couple of places in the codebase where we default to `master` - and I think we can't change them right now, in the current major version, because that would be a breaking change. The `init` command, IMHO, can be changed though - because this is targeting new users.

@janosh would you like to prepare a PR with such a change?

**Comment by BryanAdamss** [comment]
Can baseBranch set multiple values?
like 
`baseBranch:["main","master"]`

**Comment by Andarist** [comment]
I somewhat doubt it (I think that some code might depend on this being a single value and this might not be that easy to change without introducing breaking changes). What that would even mean though?
