### ISSUE TITLE
Ability to set `commit` to different values in add and version commands.

### ISSUE THREAD

**Issue by tido64** [changesets/changesets#688]
## Affected Packages

@changesets/cli

## Problem

We recently migrated to Changesets and are seeing some issues related to the `commit` option being used by both `add` and `version` commands. We set it to `true`, thinking that it would be convenient if didn't have to run `git add/commit` immediately after having run `changeset add`. But when the `action/changesets` picks up the changes and runs `changeset version`, it adds `[skip ci]` to the commit message and submits the PR. When we merge the PR, nothing happens because CI is skipped.

I looked through the docs and even looked into the code to see if I had missed a configuration somewhere, but it turns out it was removed back in 2.0, with the message below:

>   1. If you use `commit` and `skipCI` in `versionOptions` or `publishOptions`, set commit to `true`, all commits will include a skip ci message. if you have a use case for only using commit on one command or not including a skip ci message by default, contact us and we will talk about re-implementing these features.

https://github.com/atlassian/changesets/blob/678b16a6e49976bd3884919303bc22ed6690d151/packages/cli/CHANGELOG.md?plain=1#L738

So I guess what I'm asking is if we can re-implement this feature 😄 

## Proposed solution

Ability to override `commit` for one command, or at least split up the `commit` option so we can set different values for add and version commands.

**Comment by Andarist** [comment]
q: is the problem more about `commit` option affecting both commands or about `[skip ci]` being added to the commit message? It seems that you potentially want to disable the latter but using `commit: true` for both commands would be OK for you?

I'm slightly unsure why the `[skip ci]` is there - it kinda seems dangerous to me, especially as the default for the `commit` option. At least my normal workflow is that I very often include changesets together with code-oriented commits or add them quickly on top of my changes (in a separate commit) but before pushing my branch out. In both cases I definitely want the CI to run.

**Comment by tido64** [comment]
> q: is the problem more about `commit` option affecting both commands or about `[skip ci]` being added to the commit message? It seems that you potentially want to disable the latter but using `commit: true` for both commands would be OK for you?

Yes, just removing `[skip ci]` from the commit message would be enough for us. The `commit` option affecting both commands would've been fine if it wasn't for that.

> I'm slightly unsure why the [skip ci] is there

I'm also confused why it was added, tbh. I dunno if there is a use case for it.

**Comment by Andarist** [comment]
@mitchellhamilton @Noviny could you shed some context on the `[skip ci]` thing? can we just drop this? or do you believe that this would be too much of a breaking change and an option to disable the behavior is required for the v2 line?

**Comment by tido64** [comment]
@mitchellhamilton, @Noviny: Can you provide context on 👆? I'm willing to submit a PR if the change isn't too complicated.

**Comment by Andarist** [comment]
Let's wait a couple of days more to see if @mitchellhamilton responds - if not, feel free to submit a PR that removes `[skip ci]` stuff entirely. I'm debating with myself if this is going to be a breaking change or not but I'm leaning towards... no (pragmatically speaking).

**Comment by mitchellhamilton** [comment]
For `[skip ci]` in the `version` command, I believe it's due to the way some people have their CI setup to auto publish on every commit and they don't want the version commit to trigger it again. In the `add` command I'm not totally sure why it's there. Though tbh, I kinda think the right thing to do here is tell people to add a script to their `package.json` like the one below and leave `commit` as it is and discourage the usage of it.

```json
"changeset": "changeset && git add .changeset && git commit -m 'Add changeset'"
```

**Comment by tido64** [comment]
> For `[skip ci]` in the `version` command, I believe it's due to the way some people have their CI setup to auto publish on every commit and they don't want the version commit to trigger it again. In the `add` command I'm not totally sure why it's there. Though tbh, I kinda think the right thing to do here is tell people to add a script to their `package.json` like the one below and leave `commit` as it is and discourage the usage of it.

Just to be clear, `[skip ci]` is only added for the `version` command if `commit: true`. If I understand you correctly, we have two choices:

- With `commit: false`, you have to manually add and commit the change files after invoking `add` or write a script to handle it (and making sure it works across all platforms/terminals). You will need the script if you want to auto-publish on every commit.
- With `commit: true`, you don't have to manually add/commit change files, and you can auto-publish every commit. However, users of the Changesets action is out of luck because `[skip ci]` is added to the commit message when running `version`.

Users who wants to auto-commit change files, but still use the Changesets action, have to maintain an extra script regardless of what is set here. This used to work fine before 2.0, when the setting was split in two, so it feels like a regression to me. Is there really no way to get the old behaviour back? Or make it possible to customise the commit message for the `version` command?

**Comment by michaelwarren1106** [comment]
adding on here, since this is relevant to me as we speak.

I'm designing my CI build like this:

PR is created -> PR CI Build triggers -> only `changeset  status` is run

PR is merged to main -> Main CI Build Triggers -> `changeset version` && `changeset publish` are both run.

After that, the package.jsons of a bunch of components in my monorepo will have changed (the packages i created the changeset for, and dependents of those). I need to commit those back to the `main` branch. When I do, that will count as a new commit for my CI, so ANOTHER Main CI build will get triggered.

I need `[skip ci]` so that that an infinite loop doesnt start with my first main CI build.

Can we please keep this feature as a config option `skipCI: boolean | string` so that folks using different CI methods can still append `[skip ci]`? If this feature gets removed, i'm going to have to do other more complicated things like prevent the second build by checking the author of the commit against the system account that commits back to `main` from the CI job.

I'd much rather just have `[skip ci]`

**Comment by Andarist** [comment]
> the script above breaks changeset add --empty btw

Hm, why is that? I've tried that and it should work just OK since this just creates an empty changeset file in the `.changeset` directory - so it's not much different from a non-empty flow.

> PR is merged to main -> Main CI Build Triggers -> changeset version && changeset publish both run -> commit changes back to main

To understand this better - so for every PR merged in to your main branch you instantly version+publish and thus a new commit has to be added on top of you main branches cause you need to commit the result of the version command?

**Comment by tido64** [comment]
> > the script above breaks changeset add --empty btw
> 
> Hm, why is that? I've tried that and it should work just OK since this just creates an empty changeset file in the `.changeset` directory - so it's not much different from a non-empty flow.

The suggested script looks like this:

```json
"changeset": "changeset && git add .changeset && git commit -m 'Add changeset'"
```

Which means that if you do `yarn changeset add --empty`, the flags get appended to the `git` command.

**Comment by Andarist** [comment]
@tido64 thanks for clarifying!

Well, since we have existing users relying on the `[skip ci]` it seems that we can't change the default there. I agree with @mitchellhamilton's sentiment of committing being somewhat out of the scope of Changesets CLI. However, the real world ain't perfect, and plumbing flags/commands correctly with custom scripts is a chore.

You could actually plumb this specific use case "correctly" with:
```json
"changeset": "changeset",
"postchangeset": "git add .changeset && git commit -m 'Add changeset'"
```
but this is not quite obvious and makes reading the final thing more obscure as it gets spread across multiple scripts.

So I'm inclined to be in favor of making this configure/bringing old options back. I would like to hear back from @mitchellhamilton though - before we start working on this.

**Comment by tido64** [comment]
> You could actually plumb this specific use case "correctly" with:
> 
> ```json
> "changeset": "changeset",
> "postchangeset": "git add .changeset && git commit -m 'Add changeset'"
> ```
> 
> but this is not quite obvious and makes reading the final thing more obscure as it gets spread across multiple scripts.

Sadly, this won't work with all package managers. Yarn deprecated them in 2.0: https://yarnpkg.com/advanced/lifecycle-scripts

> So I'm inclined to be in favor of making this configure/bringing old options back.

Agreed. It does look like this is the only option left.

**Comment by Andarist** [comment]
> Sadly, this won't work with all package managers. Yarn deprecated them in 2.0: https://yarnpkg.com/advanced/lifecycle-scripts

Today I Relearned

**Comment by michaelwarren1106** [comment]
> To understand this better - so for every PR merged in to your main branch you instantly version+publish and thus a new commit has to be added on top of you main branches cause you need to commit the result of the version command?

Basically yeah. It wont be every single PR, it'll just be PRs that contain changesets that would auto version/publish. I don't think it really matters whether or not its every single PR, or every PR that contains a changeset. The issue at hand is that for a lot of CI builds, if you're triggering a build to happen on a commit/merge/push to a branch, then EVERY commit/merge/push to that branch triggers a build unless there's some way to stop it. So if your CI build commits anything back to the repo (like automated version bumped package.json files and changelogs) then that would start another build automatically unless there's some way to prevent it.

**Comment by rohit-gohri** [comment]
I'll be interested in an option to disable addition of "[skip ci]" while keeping the auto commit functionality. My usecase is like this:

`changeset version` runs on CI whenever someone opens a PR from `develop` (staging env) -> `main` (prod env) and pushes back the result to `develop` branch. 

Due to the `[skip ci]` the pipeline gets skipped and the required CI checks in Github Branch protection rules fail
<img width="877" alt="image" src="https://user-images.githubusercontent.com/31949290/149190237-fc24bee7-e644-4ec2-bfc2-7811b13e27a0.png">

One solution I think that would fit most use cases is to be able to customize the commit message template itself rather add a specific option for `[skip ci]`. Something similar to the changelog option?

**Comment by rohit-gohri** [comment]
I created a PoC based on that idea: https://github.com/changesets/changesets/pull/735

**Comment by picosam** [comment]
Hello! Any updates on merging this?

**Comment by maximveksler** [comment]
To shorten the search space for people looking to disable skip-ci when they merge the changesets pull requesst.

Add this to your config.json

```
  "commit": ["@changesets/cli/commit", { "skipCI": false }],
```

This will disable the flag for both `changeset add` and `changeset version` actions.

Disabling for `add` makes sense for the scenario when developer has finished working on the feature, and than follows to doucment the change. In this case, if skip-ci is activated no checks will run, so the PR is blocked from merge (when protections are enabled, on Github)

Disabling for `version` makes sense because our CI/CD flow is designed to trigger on "Version Packages" merge.


```yaml
name: WIP- Release

on:
  workflow_run:
    workflows:
      - Tests
    types: [completed]
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && (startsWith(github.event.workflow_run.head_commit.message, 'Version Packages') || contains(github.event.workflow_run.head_commit.message, '#release')) }}
    steps:
```
