### ISSUE TITLE
Error messages are not human readable

### ISSUE THREAD

**Issue by BlackGlory** [changesets/changesets#737]
@changesets/cli 2.19.0
```
🦋  info Publishing "@middleware/stream" at "0.11.2"
🦋  error an error occurred while publishing @middleware/stream: 1 command failed 
🦋  error sh -c yarn run-s clean build
🦋  error <Buffer 45 52 52 4f 52 3a 20 22 62 75 69 6c 64 3a 63 6f 6d 70 69 6c 65 22 20 65 78 69 74 65 64 20 77 69 74 68 20 32 2e 0a 45 52 52 4f 52 3a 20 22 62 75 69 6c ... 488 more bytes>
🦋  error packages failed to publish:
🦋  @middleware/stream@0.11.2
error Command failed with exit code 1
```

**Comment by Andarist** [comment]
@BlackGlory could you create a repro case for this problem?

**Comment by BlackGlory** [comment]
I'm afraid I can't create it, because this error only appears on publish, and disappears after multiple calls.

**Comment by Andarist** [comment]
I've managed to find the place where that Buffer could indeed be logged "as is" and I've prepared a fix for this: https://github.com/changesets/changesets/pull/760

Hopefully, with this patch released soon-ish you could get more info about your particular problem. Note that recently we go a similar report here: https://github.com/changesets/changesets/issues/759. Perhaps your problem is the same?

**Comment by BlackGlory** [comment]
I think it is the same.

**Comment by Andarist** [comment]
So you are using snap too?

**Comment by BlackGlory** [comment]
My Node.js v16.13.1 is installed via nvm, so this may not be relevant to snap.

**Comment by JakeGinnivan** [comment]
FWIW I am using GitHub actions with

```
            - name: Setup Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  registry-url: 'https://npm.pkg.github.com'
```

After this PR I am getting

```
🦋  error 
🦋  error 
🦋  error packages failed to publish:
```

The packages are not published yet so this is the initial publish. Will update when get to the bottom of why it's failing (assume it's a token/scoping/npmrc issue or similar)

**Comment by JakeGinnivan** [comment]
Ok, mine was interesting.

PNPM wasn't returning an error when `--json` was passed to the publish command. The issue was I was setting `publishConfig.directory` because NX builds to a dist folder, but it's not removing that from the copied package.json so it then tried to follow the publishConfig.directory again which resulted in a path which didn't exist

**Comment by Andarist** [comment]
Hm, the `--json` issue sounds like something is wrong with how pnpm handles this flag, right? As to the `publishConfig.directory` problem - did you manage to fix this on your end?

**Comment by JakeGinnivan** [comment]
Heh, well after the `build` step I ran this script

```
import { writeFile, readFile } from 'node:fs/promises'
import {} from 'node:path'
;(async function () {
    await removePublishDir('dist/libs/nx-terraform/package.json')
    await removePublishDir('dist/libs/nx-workspace/package.json')
})()

async function removePublishDir(nxTerraformPackageJsonName: string) {
    const packageJson = await readFile(nxTerraformPackageJsonName)
    const packageJsonParsed = JSON.parse(packageJson.toString())
    delete packageJsonParsed.publishConfig.directory
    await writeFile(
        nxTerraformPackageJsonName,
        JSON.stringify(packageJsonParsed, null, 4)
    )
}
```

Bit of a hack. I will raise an issue about --json hiding errors for pnpm actually, the directory one is a NX problem
