### ISSUE TITLE
Cannot publish package dependent on new version of another package in same changeset

### ISSUE THREAD

**Issue by imthinhvu** [changesets/changesets#837]
## Affected Packages

https://github.com/BitskiCo/bitski-js
- packages/browser
- packages/provider

## Problem

When going to publish a changeset, my `browser` package fails on `npm install` because it depends on the latest version of my `provider` package which is part of the same changeset. Can I somehow specify an order in which the package gets published, or are there any other native ways to get this playing nicely?

## Proposed solution

???

**Comment by imthinhvu** [comment]
@Andarist - you can see what I'm referring to here: https://github.com/BitskiCo/bitski-js/runs/6863876438?check_suite_focus=true

I don't particularly think this is an issue with `changesets` - more so wondering if there are capabilities and/or additional knowledge I'm missing of getting interdependent packages to play nicely with each other.

Essentially, if we have to update both packages, it currently means we can't include them both in the same changeset and would have to do it one at a time - `provider` first, and then `browser` since `browser` depends on the updated version of `provider`. I was trying to see if I can somehow publish them together despite this restriction.

The furthest I could ween from the docs is wrt `linked packages` -- but it was not immediately clear to me whether this addressed my problem: https://github.com/changesets/changesets/blob/main/docs/linked-packages.md

**Comment by Andarist** [comment]
> Essentially, if we have to update both packages, it currently means we can't include them both in the same changeset and would have to do it one at a time - provider first, and then browser since browser depends on the updated version of provider. I was trying to see if I can somehow publish them together despite this restriction.

Yes, publishing them together is the easiest - publishing them in a "waterfall" manner would be quite complex to manage.

> The furthest I could ween from the docs is wrt linked packages -- but it was not immediately clear to me whether this addressed my problem: https://github.com/changesets/changesets/blob/main/docs/linked-packages.md

It doesn't - it's just a way to change what the computed versions end up being but with this option, you still version the whole monorepo "at once".

---

If you could prepare a very barebones repo based on npm workspaces, with some dummy public packages in it - then it would allow me to investigate this sooner than later.

**Comment by kachkaev** [comment]
Seeing this issue in [blockprotocol/blockprotocol](https://github.com/blockprotocol/blockprotocol). 

- [Version Pacakges PR](https://github.com/blockprotocol/blockprotocol/pull/513)
- [Release action](https://github.com/changesets/changesets/issues/837) – it succeeded only after Attempt 4 and failed three times initially

<img width="364" alt="Screenshot 2022-08-22 at 11 42 50" src="https://user-images.githubusercontent.com/608862/185902959-f4baa228-549c-41a9-9cb5-6c91602b0f1e.png">

Our `package.json`s have the `prepare` script, which recreate the contents of corresponding `dist` folders. Since all changed packages are published in parallel, multiple `prepare` scripts run simultaneously and some packages fail to build because `dist` folders in upstream packages are being recreated.

This should be fixable if packages are published sequentially (ideally, following the dependency tree). AFAIU, Lerna does it this way, at least I don’t remember this issue with it in projects I’ve worked on.

In the meantime, we have to re-run the Release script till it settles. @Andarist what else would you recommend?

**Comment by Andarist** [comment]
We could accept a PR that would publish packages in a topological order. If you don't intend to prepare a PR for this then I would recommend you to remove your `prepare` scripts from packages and just run a single monorepo-wide build before you call `changeset publish`.

**Comment by imthinhvu** [comment]
Going to close this as it ended up being an issue with our prepack scripts as well. Removing that enabled the topological order in turborepo with changeset.

**Comment by kachkaev** [comment]
@imthinhvu what is your recipe for publishing packages in topological order with Turborepo? I'd love to borrow that.

**Comment by imthinhvu** [comment]
> @imthinhvu what is your recipe for publishing packages in topological order with Turborepo? I'd love to borrow that.

There's nothing magical we're doing - turborepo should support topological build: https://turborepo.org/docs/core-concepts/pipelines#topological-dependency

What we've added is a `release` npm script that does `turbo run build && changeset publish`
