### ISSUE TITLE
TypeError: Cannot read property 'packageJson' of undefined

### ISSUE THREAD

**Issue by fupengl** [changesets/changesets#841]
## Affected Packages

```json
{
  "devDependencies": {
    "@changesets/cli": "^2.23.0",
    "typescript": "4.7.3"
  }
}
```
node `v14.19.3`
pnpm `v7.2.1`
pc `Apple M1 Pro`

## Problem

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/20211964/174001558-b165de9e-db3d-4c30-b00d-d513b4af5cbe.png">

```sh
🦋  error TypeError: Cannot read property 'packageJson' of undefined
🦋  error     at createChangeset (/Users/fupeng/Workspace/github/silly-girl/node_modules/.pnpm/@changesets+cli@2.23.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:415:75)
🦋  error     at add (/Users/fupeng/Workspace/github/silly-girl/node_modules/.pnpm/@changesets+cli@2.23.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:507:26)
🦋  error     at processTicksAndRejections (internal/process/task_queues.js:95:5)
🦋  error     at async run$2 (/Users/fupeng/Workspace/github/silly-girl/node_modules/.pnpm/@changesets+cli@2.23.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1254:5)
```

**Comment by mahboobmonnamd** [comment]
The reason may be for this
1. Package.json file is not at the root level
2. If it is mono repo, package.json should be available within the each service folder

**Comment by fupengl** [comment]
mono repo project
changesets are installed in the root directory
The rest of the subpackages also have package.json

**Comment by mahboobmonnamd** [comment]
Check do you have workspace file. I use pnpm. So i have pnpm-workspace.yaml.

**Comment by fupengl** [comment]
I am also pnpm, workspace related declarations are normal
I was wondering if it was a problem with my nodejs version, I migrated from lerna

**Comment by mahboobmonnamd** [comment]
I had this issue, i resolved after doing the above steps. writing it again to ensure you too follow the same
1. have pnpm-workspace.yaml, should have references to those repos
2. install @changeset/cli
3. Added package.json inside the service repos

**Comment by fupengl** [comment]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/20211964/178671429-a440da61-5bb2-4082-8e1c-60f0d86dcdd3.png">

Thanks for your reply, I will try again
The corresponding files and dependencies should be complete

**Comment by mahboobmonnamd** [comment]
https://github.com/mahboobmonnamd/monorepo-js check this it may help you

**Comment by fupengl** [comment]
Thanks guy

**Comment by liansky** [comment]
@fupengl  Has the problem been solved？

**Comment by Andarist** [comment]
We need a repro case to look into this.

**Comment by hcharley** [comment]
I have a repro here @Andarist https://github.com/hcharley/changesets-issue-841/runs/7570186130?check_suite_focus=true

**Comment by ijisen** [comment]
in my root package.json has this config :  "workspaces": [ "packages/" ];  when i run " npx changeset", there has err "TypeError: Cannot read properties of undefined (reading 'packageJson');"

so, i try to change "workspaces": [ "packages/" ]  => "workspaces": [ "packages/*" ]  or delete this config, the are working!!

**Comment by notaphplover** [comment]
In my case, no packages with versions were found. The error is not very developer friendly and the issue should be easy to solve. As @Andarist said, repro steps are needed to recreate any issue. Having said that, can we have a look to the code?

Consider:

**packages/cli/src/commands/add/createChangeset.ts**
```typescript
export default async function createChangeset(
  changedPackages: Array<string>,
  allPackages: Package[]
): Promise<{ confirmed: boolean; summary: string; releases: Array<Release> }> {
  const releases: Array<Release> = [];

  if (allPackages.length > 1) {
  // Code omitted
  } else {
    let pkg = allPackages[0];
    
    // Code omitted
  }
}
```

The source code falsely asumes pkg is a Package. It can perfectyl be undefined since `allPackages` can be an empty array. Consider using [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess).

This is particulary true to some flows where no package is eligible since 

**packages/cli/src/commands/add/index.ts**
```typescript
  const changedPackagesName = changedPackages
      .filter((pkg) => isListablePackage(config, pkg.packageJson))
      .map((pkg) => pkg.packageJson.name);
  newChangeset = await createChangeset(changedPackagesName, listablePackages);
```

the `add` function can filter out all the packages detected.

### Proposed solution

For the sake of a better developer experience, what about updating `createChangeset` to throw a meaningfull error in case no package is detected?

**packages/cli/src/commands/add/createChangeset.ts**
```typescript
export default async function createChangeset(
  changedPackages: Array<string>,
  allPackages: Package[]
): Promise<{ confirmed: boolean; summary: string; releases: Array<Release> }> {
  const releases: Array<Release> = [];

 if (allPackages.length === 0) {
   throw new MeaningfullError('Super duper description!');
 }

  if (allPackages.length > 1) {
  // Code omitted
  } else {
    let pkg = allPackages[0];
    
    // Code omitted
  }
}
```

This may be suficient for getting a better experience, but we could even iterate this solution to a (imo) better one. Imo, we should not change the fact `createChangeset` must fail if an empty array but, what if this error is catched in order to throw an even more meaningful error? As discussed earlier, the `add` function (at `packages/cli/src/commands/add/index.ts`) knows the potential listed packages, and the filtered packages. What if we catch the error thrown on `createChangeset` in order to throw an error informing the use the list of detected packages and a message telling that no package was eligible to add changes? This way we would defend ourselves from wrong `createChangeset` inputs while we deliver a developer friendly error message.

I'm more than open to go with a PR @Andarist :heart:

**Comment by yunsii** [comment]
My repo https://github.com/yunsii/fasttext.wasm.js encounter the samle error, because root packages.json should be released, but after create `beach` workspace as internal package and add `bench` to ignore, it throw the error when I run `npx changset`.

Even without ignore `bench`, it only release `bench`, no root package anymore……

**Comment by yunsii** [comment]
I found a workaround, delete `pnpm-workspace.yaml` before release, restore it after release completed 😂

**Comment by yunsii** [comment]
> I found a workaround, delete `pnpm-workspace.yaml` before release, restore it after release completed 😂

Follow the logic, I add workspace `.` to `pnpm-workspace.yaml` and restore changset ignore config, it works like a charm, refer to https://github.com/yunsii/fasttext.wasm.js/commit/5e1dd82625011175af03bdb28fb819cb1f933182

**Comment by battis** [comment]
fwiw, I ran into this error because of a malformed root `package.json`. Since I was also using `pnpm`, I had missed that the `workspaces` entry _must_ be an array:

```json
{
  "workspaces": [
    "packages/*"
  ]
}
```

**Comment by ayushnau** [comment]
what works for me. is the name of the package that i had was not of the same account that i had the npm token of. fixing it that is chagning the name to the account that i am using npm token fixed it for me.

**Comment by kevinpastor** [comment]
> Follow the logic, I add workspace `.` to `pnpm-workspace.yaml` and restore changset ignore config, it works like a charm, refer to [yunsii/fasttext.wasm.js@5e1dd82](https://github.com/yunsii/fasttext.wasm.js/commit/5e1dd82625011175af03bdb28fb819cb1f933182)

This seems to be a weird workaround since [the pnpm-workspace.yaml documentation](https://pnpm.io/pnpm-workspace_yaml#:~:text=The%20root%20package%20is%20always%20included) states that the root package is always included.

About the `workspaces` property in the root `package.json` file, for PNPM, this is irrelevant since the `pnpm-workspace.yaml` file occupies this role.

If anyone has a solution that doesn't rely on a workaround or on duplication of configuration, that would be appreciated.

**Comment by kevinpastor** [comment]
I fixed my issue by going through the changeset files. I had previously manually changed one of them and made a typo in the package name.

**Comment by bnonni** [comment]
> I fixed my issue by going through the changeset files. I had previously manually changed one of them and made a typo in the package name.

This worked for me!

**Comment by raulfdm** [comment]
My case:

1. I had a package `a`
2. Created a changeset for `a`
3. renamed the package `a` to `b`
4. changeset was still pointing `a`
5. `Cannot destructure property 'packageJson' of 'undefined' as it is undefined`

To fix I just remove the changeset (since I'll be starting over the publish)
