### ISSUE TITLE
`changeset publish` and `changeset version` do not run package.json `prepublish` or `version` scripts

### ISSUE THREAD

**Issue by silesky** [changesets/changesets#860]
Thanks for your work on this.

NPM lifecycle scripts do not seem to work. When I run a command like `changeset publish` on a repo using yarn workspaces, I'm not seeing any prepublish scripts run. When I do `yarn workspace <workspace_name> exec npm publish`, the prepublish scripts run as usual.

## Affected Packages
`@changesets/cli`
 https://github.com/changesets/changesets/tree/main/packages/cli/src/commands/publish

## Problem

Running `changeset publish` or  `changeset version` does not trigger any npm lifecycle scripts.

**Comment by silesky** [comment]
Sure @Andarist. Yes, I’ve tried it with prepare.

Repro: https://github.com/segmentio/analytics-next
- clone repo
- yarn install
- yarn changeset (select analytic-next package),
-  yarn changeset version && git add . && git commit -m “foo”
- yarn changeset publish (NPM auth error aside, pre publish / prepare scripts should run before this).

**Comment by silesky** [comment]
@Andarist this looks like a node/npm issue; it works on npm 8 and up (node 17), but not npm 6 or 7.

**Comment by Andarist** [comment]
Hm, I've just tested with npm 6 in your repo and I still get the same result.

**Comment by awxalbert** [comment]
Run into the same problem, not sure if we're in the same context when running the script, but after some digging, I found the problem probably related to run `changeset publish` in CI system like gitlab CI. So in general, npm will not execute lifecycle hooks when it's executed in root role. (in early npm versions before npm@7 ?), so maybe that's why it worked in the local. It's not a problem for `changeset`, just post the results here so anybody can reference this in the future.

related topics:
- https://github.com/semantic-release/semantic-release/issues/956
- https://github.com/npm/npm/issues/3497

potential solutions:
- set [unsafe-perm](https://docs.npmjs.com/cli/v6/using-npm/config#unsafe-perm) to `true`
- just run `yarn build` before publish
